### ISSUE TITLE
sklearn is deprecated in setup.py

### ISSUE THREAD

**Issue by kbamps** [JeroenBertels/deepvoxnet2#1]
When installing DeepVoxNet2, users encounter a deprecation warning related to the 'sklearn' PyPI package. The warning suggests using 'scikit-learn' instead of 'sklearn' for pip commands due to the deprecation of the 'sklearn' package.

## The error:
        The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
          rather than 'sklearn' for pip commands.
          
          Here is how to fix this error in the main use cases:
          - use 'pip install scikit-learn' rather than 'pip install sklearn'
          - replace 'sklearn' by 'scikit-learn' in your pip requirements files
            (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
          - if the 'sklearn' package is used by one of your dependencies,
            it would be great if you take some time to track which package uses
            'sklearn' instead of 'scikit-learn' and report it to their issue tracker
          - as a last resort, set the environment variable
            SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
          
          More information is available at
          https://github.com/scikit-learn/sklearn-pypi-package
        
        Update the 'sklearn' dependency to 'scikit-learn' in the setup.py file.

### setup.py snippet
install_requires=[
    # ... other dependencies
    'scikit-learn',
    # ... other dependencies
],

Groetjes,
Kobe

**Comment by JeroenBertels** [comment]
Thanks, Kobi! Should be fixed in version deepvoxnet2-2.15.0 :-)
